### ISSUE TITLE
panic on `ilex_xml::parse_trimmed`

### ISSUE THREAD

**Issue by rfuzz** [alexanderjkslfj/ilex#1]
Hi,

While performing fuzz testing on this crate, I encountered a panic scenario: when parsing invalid XML (missing closing tags) using `ilex_xml::parse_trimmed`, the function causes a panic.

For example:

```rust
use ilex_xml::parse_trimmed;
fn main() {
    let xml = r#"
<parent>
"#;

    if let Ok(_items) = parse_trimmed(xml) {
        println!("OK!");
    };
}
```

After running this, I got the following output:

```shell
thread 'main' panicked at /home/ubuntu/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/ilex_xml-0.4.0/src/parsing.rs:38:34:
index out of bounds: the len is 1 but the index is 1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Here’s the version information I’m using:

```toml
[dependencies]
ilex_xml = "0.4.0"
```

**Comment by alexanderjkslfj** [comment]
Hey, thanks for the report!
The issue should be fixed in the latest version.
